# Generated by Django 3.1.7 on 2021-03-27 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoapp',
            name='todolist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todoapp.category'),
        ),
        migrations.AlterField(
            model_name='todoapp',
            name='title',
            field=models.CharField(default='DEFAULT VALUE', max_length=250),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
