# Generated by Django 3.1.7 on 2021-03-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20210327_1817'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoApp',
            new_name='TodoItem',
        ),
    ]
